name: First Workflow
env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: First Job Script
        shell: bash
        run: echo "Hello world! This is the first job"

      - name: Greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Mona the Octocat"

      - name: Show Greeting Time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env: 
      JOB_VAR: "This is a job variable"
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Second Job Script
        shell: bash
        run: |
          echo "Segunda prueba"
          echo "Otra línea"

      - name: Environmental Variables
        env: 
          STEP_VAR: "This variable is declared at the step level"
        run: |
          echo "Workflow Variable: $WORKFLOW_VAR"
          echo "Job Variable: $JOB_VAR"
          echo "Step Variable: $STEP_VAR"
          echo "Secret: ${{ secrets.SOME_SECRET }}"
          echo "GitHub Actor: $GITHUB_ACTOR"
          echo "GitHub Job: $GITHUB_JOB"
          echo "GitHub Ref: $GITHUB_REF"
