name: first workflow
env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"
on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello world This is the first job
      - name: checkout
        uses: actions/checkout@v4
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Mona the Octocat"
      - name: time
        run: |
          echo "The time of th greeting was at: ${{ steps.greetings.output.time }}"

  
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env: 
      JOB_VAR: "This is a job variable"
    steps:
      - name: second
        shell: bash
        run: |
          echo segunda prueba
          echo otra linea
      - name: environmental variables
        env: 
          STEP_VAR: "This variable is declared at the step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "secret:  ${{secrets.SOME_SECRET }} 
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF






  
